### ISSUE TITLE
Not able to update translations

### ISSUE THREAD

**Issue by ma-vie** [mamantoha/zci#22]
Hello,

I'm not  able to  update the translations. 
Info:

- Crowdin default language: **de**
- Crowdin translation language: **en**  locale: en-US
-----------------------------------------------
- Zendesk default language **de**
- Zendesk translations language **en** -> locale: en-US

-----------------------------------------------

![image](https://user-images.githubusercontent.com/45437669/61203528-ec634e80-a6ea-11e9-85b4-017618021597.png)

 import:sources               - works
 download:translations   - works
 export:translations         - fails

Api request logs:
![image](https://user-images.githubusercontent.com/45437669/61203264-2bdd6b00-a6ea-11e9-8f24-585b84a2e62a.png)

thank you in advance

**Comment by mamantoha** [comment]
Hi @ma-vie .

Thanks for the report.
Can you update `zci` to `0.9.0` and let me know if this resolves your issue?

**Comment by ma-vie** [comment]
Hi @mam, 
Thanks for the fast reply.
I updated the new Version but i'm getting this error:

![image](https://user-images.githubusercontent.com/45437669/61293936-0d07d300-a7d5-11e9-99c9-73259884f264.png)


thank you in advance

**Comment by mamantoha** [comment]
Sorry, my bad.
I will release fix in a hour.

**Comment by mamantoha** [comment]
@ma-vie please try `0.10.0`

**Comment by ma-vie** [comment]
@mamantoha 
Thank you, i will try now

**Comment by ma-vie** [comment]
Perfect :) it works now!

I think there is an encoding issue?

From xml file:
![image](https://user-images.githubusercontent.com/45437669/61299541-92dd4b80-a7e0-11e9-8c41-5f97730e6bdd.png)

also in zendesk uploaded translation:
![image](https://user-images.githubusercontent.com/45437669/61299700-e2237c00-a7e0-11e9-9462-15979c39ceb9.png)

**Comment by mamantoha** [comment]
Probably, yes. Can you create another issue with some information on how to reproduce this?
