### ISSUE TITLE
"No such category"

### ISSUE THREAD

**Issue by asujata** [mamantoha/zci#6]
When calling "zci import:sources" I always get error: No such category found even though I'm pretty sure that the category id is correct.

The URL to the category is: https://sell-ina.zendesk.com/hc/de/categories/201149189-Test and the category id I used in zci.yml is 201149189.

Do you have any idea what I'm doing wrong or is that a known problem?

Thanks,
Andreas

**Comment by asujata** [comment]
The problem was a wrong zendesk_base_url. See my pull request: https://github.com/mamantoha/zci/pull/7

**Comment by mamantoha** [comment]
Merged. Thanks.
